# Generated by Django 5.1.1 on 2024-11-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disliked_ingredients',
            field=models.ManyToManyField(related_name='disliked_by', through='api.DislikedIngredients', to='api.ingredient'),
        ),
    ]
