# Generated by Django 5.1.1 on 2024-11-11 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNutrientPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_calories', models.IntegerField(blank=True, null=True)),
                ('max_calories', models.IntegerField(blank=True, null=True)),
                ('min_sugars', models.IntegerField(blank=True, null=True)),
                ('max_sugars', models.IntegerField(blank=True, null=True)),
                ('min_protein', models.IntegerField(blank=True, null=True)),
                ('max_protein', models.IntegerField(blank=True, null=True)),
                ('min_iron', models.IntegerField(blank=True, null=True)),
                ('max_iron', models.IntegerField(blank=True, null=True)),
                ('min_potassium', models.IntegerField(blank=True, null=True)),
                ('max_potassium', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
