# Generated by Django 5.1.1 on 2024-12-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cart_cartingredient_cart_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartingredient',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
