# Generated by Django 5.1.1 on 2024-12-03 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dayplanrecipes',
            name='day_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='api.dayplan'),
        ),
        migrations.AlterUniqueTogether(
            name='dayplan',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='dayplanrecipes',
            unique_together={('day_plan', 'recipe')},
        ),
    ]
