# Generated by Django 5.1.1 on 2024-12-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userrecipeusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernutrientpreferences',
            name='diet_type',
            field=models.CharField(choices=[('keto', 'Keto'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('high_protein', 'High Protein'), ('balanced', 'Balanced')], default='balanced', max_length=20),
        ),
    ]
