# Generated by Django 5.1.1 on 2025-01-11 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_usernutrientpreferences_diet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='carbohydrates',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='fiber',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_calories', models.FloatField(default=0.0)),
                ('total_carbohydrates', models.FloatField(default=0.0)),
                ('total_fat', models.FloatField(default=0.0)),
                ('total_protein', models.FloatField(default=0.0)),
                ('total_fiber', models.FloatField(default=0.0)),
                ('total_sugars', models.FloatField(default=0.0)),
                ('total_iron', models.FloatField(default=0.0)),
                ('total_potassium', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
