# Generated by Django 5.1.1 on 2025-01-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_recipe_carbohydrates_recipe_fat_recipe_fiber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernutrientpreferences',
            name='max_carbohydrates',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernutrientpreferences',
            name='max_fat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernutrientpreferences',
            name='max_fiber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernutrientpreferences',
            name='min_carbohydrates',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernutrientpreferences',
            name='min_fat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernutrientpreferences',
            name='min_fiber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
