# Generated by Django 5.1.1 on 2025-01-11 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_usernutrientpreferences_max_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernutrientpreferences',
            name='diet_type',
            field=models.CharField(choices=[('low_calories', 'Low Calories'), ('high_calories', 'High Calories'), ('high_protein', 'High Protein'), ('low_fat', 'Low Fat'), ('high_fat', 'High Fat'), ('low_carbohydrates', 'Low Carbohydrates'), ('high_carbohydrates', 'High Carbohydrates')], default='balanced', max_length=20),
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('total_calories', models.FloatField(default=0.0)),
                ('total_carbohydrates', models.FloatField(default=0.0)),
                ('total_fat', models.FloatField(default=0.0)),
                ('total_protein', models.FloatField(default=0.0)),
                ('total_fiber', models.FloatField(default=0.0)),
                ('total_sugars', models.FloatField(default=0.0)),
                ('total_iron', models.FloatField(default=0.0)),
                ('total_potassium', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'week_start')},
            },
        ),
        migrations.DeleteModel(
            name='DailySummary',
        ),
    ]
