# Generated by Django 5.1.1 on 2025-01-11 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_usernutrientpreferences_diet_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('total_calories', models.FloatField()),
                ('total_protein', models.FloatField()),
                ('total_fats', models.FloatField()),
                ('total_carbs', models.FloatField()),
                ('total_sugars', models.FloatField()),
                ('total_iron', models.FloatField()),
                ('total_potassium', models.FloatField()),
                ('day_plan_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.dayplanrecipes')),
            ],
            options={
                'unique_together': {('day_plan_recipe', 'item_name')},
            },
        ),
    ]
