# Generated by Django 5.1.1 on 2025-01-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_dayplanitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dayplanitem',
            unique_together=set(),
        ),
    ]
