# Generated by Django 5.1.1 on 2025-01-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_dayplanitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplanitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='dayplanitem',
            unique_together={('day_plan_recipe', 'item_name')},
        ),
    ]
