# Generated by Django 5.1.1 on 2025-01-11 22:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_dayplanitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dayplanitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dayplanitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dayplanitem',
            name='total_carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dayplanitem',
            name='total_fats',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dayplanitem',
            name='total_iron',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dayplanitem',
            name='total_potassium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dayplanitem',
            name='total_protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dayplanitem',
            name='total_sugars',
            field=models.FloatField(default=0),
        ),
        migrations.RemoveField(
            model_name='dayplanitem',
            name='day_plan_recipe',
        ),
    ]
