# Generated by Django 5.1.1 on 2025-01-11 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_dayplanitem_unique_together_dayplanitem_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplanitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
