# Generated by Django 5.1.1 on 2025-01-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_dayplanitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplanitem',
            name='total_fiber',
            field=models.FloatField(default=0),
        ),
    ]
