# Generated by Django 5.1.1 on 2025-01-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_dayplanitem_total_fiber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useringredients',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='useringredients',
            name='user',
        ),
        migrations.AlterField(
            model_name='usernutrientpreferences',
            name='diet_type',
            field=models.CharField(choices=[('low_calories', 'Low Calories'), ('high_calories', 'High Calories'), ('high_protein', 'High Protein'), ('low_fat', 'Low Fat'), ('high_fat', 'High Fat'), ('low_carbohydrates', 'Low Carbohydrates'), ('high_carbohydrates', 'High Carbohydrates')], default='high_protein', max_length=20),
        ),
        migrations.AlterField(
            model_name='usernutrientpreferences',
            name='max_calories',
            field=models.IntegerField(default=2500),
        ),
        migrations.AlterField(
            model_name='usernutrientpreferences',
            name='max_carbohydrates',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usernutrientpreferences',
            name='max_fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usernutrientpreferences',
            name='max_fiber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usernutrientpreferences',
            name='max_iron',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usernutrientpreferences',
            name='max_potassium',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usernutrientpreferences',
            name='max_protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usernutrientpreferences',
            name='max_sugars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usernutrientpreferences',
            name='min_calories',
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name='usernutrientpreferences',
            name='min_carbohydrates',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usernutrientpreferences',
            name='min_fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usernutrientpreferences',
            name='min_fiber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usernutrientpreferences',
            name='min_iron',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usernutrientpreferences',
            name='min_potassium',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usernutrientpreferences',
            name='min_protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usernutrientpreferences',
            name='min_sugars',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='RatedRecipes',
        ),
        migrations.DeleteModel(
            name='UserIngredients',
        ),
    ]
