version: "3"

services:
  backend:
    build:
      context: . # Global context
      dockerfile: Dockerfile.backend # Referencing the Dockerfile in the global root
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mydb
    depends_on:
      - db

  frontend:
    build:
      context: . # Global context
      dockerfile: Dockerfile.frontend # Referencing the Dockerfile in the global root
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5433:5433"
